rootProject.name = "playground"
include("playground-server")
include("ratelimiter")
include("httpinterface")
include("beanprocessor")
include("functionalconfig")
include("webflux-world")
include("cloud-stream-kafka")
include("rule-engine")
include("fallbackcache")
include("bulkhead")
include("retry")
include("hunit5")
include("annotation-validator")
