spring:
  cloud:
    function:
      definition: orderCreated;
    stream:
      bindings:
        orderCreated-in-0:
          destination: order-created
          group: order-group
          content-type: application/*+avro
          consumer:
            retryable-exceptions:
              java.lang.IllegalArgumentException: false
              java.lang.RuntimeException: true
        orderCreated-out-0:
          destination: order-created
          content-type: application/*+avro
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            schema.registry.url: http://localhost:8081
        bindings:
          orderCreated-in-0:
            consumer:
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                group.id: order-group
                auto.offset.reset: earliest
                max.poll.records: 1
                session.timeout.ms: 5000
                heartbeat.interval.ms: 5000
              enableDlq: true
              dlqName: order-created-dlq
