lock:
  instances:
    point:
      provider: redis
      key: point
      waitTime: 2000
      leaseTime: 1000
    promotion:
      provider: mysql
      key: promotion
      waitTime: 1000
      leaseTime: 1000
